variables:
  major: 1
  minor: 0
  patch: $[counter(format('major {0} minor {1}', variables['major'], variables['minor']), 0)]

name: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self
    clean: true

trigger:
  - main

pr: none

steps:
  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: "ci"

  - task: Npm@1
    displayName: "npm run typecheck"
    inputs:
      command: "custom"
      customCommand: "run typecheck"

  - task: Npm@1
    displayName: "npm run lint"
    inputs:
      command: "custom"
      customCommand: "run lint"

  - task: Npm@1
    displayName: "npm test"
    inputs:
      command: "custom"
      customCommand: "test"

  - task: Npm@1
    displayName: "npm run build"
    inputs:
      command: "custom"
      customCommand: "run build"

  - task: Npm@1
    displayName: "npm set version to build number"
    inputs:
      command: "custom"
      customCommand: "version $(Build.BuildNumber) --no-git-tag-version"

  - task: Npm@1
    displayName: "npm publish"
    inputs:
      command: "publish"
      publishEndpoint: "carl-hartshorn npm"
