variables:
  prbuildnumber: $[counter('pr', 1)]

name: $[format('PR - {0}', variables['prbuildnumber'])]

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self
    clean: true

trigger: none

pr:
  - main

steps:
  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: "ci"

  - task: Npm@1
    displayName: "npm lint"
    inputs:
      command: "custom"
      customCommand: "run lint"

  - task: Npm@1
    displayName: "npm test"
    inputs:
      command: "custom"
      customCommand: "test"

  - task: Npm@1
    displayName: "npm run build"
    inputs:
      command: "custom"
      customCommand: "run build"
